### ISSUE TITLE
Feature for postgres: on conflict update

### ISSUE THREAD

**Issue by reactormonk** [tathougies/beam#115]
See https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT - aka UPSERT.

**Comment by tathougies** [comment]
This already exists: https://github.com/tathougies/beam/blob/af268200143d54179a4e43d1904c48ca73ed2652/beam-postgres/Database/Beam/Postgres/Syntax.hs#L1259

Example usage:

```
import Database.Beam hiding (insert)
import Database.Beam.Postgres (insert, onConflictUpdateInstead, onConflictSet)

insert (_table1 db) (insertValues [row1, row2, row3])
      (onConflictUpdateInstead (\tbl -> (field1 tbl, field2 tbl)))
```

The argument to `onConflictUpdateInstead` specifies which fields should be updated. You can also explicitly decide what to set. For example, to keep a running sum instead of overwriting a particular value.


```
import Database.Beam hiding (insert)
import Database.Beam.Postgres (insert, onConflictUpdateInstead, onConflictSet)

insert (_table1 db) (insertValues [row1, row2, row3])
      (onConflictSet (\curTbl insertingRow -> [ field1 curTbl <-. field1 insertingRow, field2 curTbl <-. current_ (field2 curTbl) + field2 insertingRow]))
```

**Comment by tathougies** [comment]
Do feel free to open a new issue if this doesn't work

**Comment by reactormonk** [comment]
Sorry, I was searching by "conflict" on github, that didn't find anything.
