### ISSUE TITLE
Wanting to implement Firebird backend support

### ISSUE THREAD

**Issue by gibranrosa** [tathougies/beam#14]
Hi! I have forked the Master branch  at the beginning of March, and haven't notticed  you have started to work on the library again. I would like to know if I already can try to adapt my preliminary Firebird backend with the modifications in the branch travis/beam-0500.

And I would be glad to be one of the contributors responsible for the Firebird backend support.
Thanks!

**Comment by tathougies** [comment]
Hi, 

I've been working actively on the travis/beam-0500 branch. I'm working on some documentation, including how to create a backend. There's already sample backends for both postgres and sqlite.

I also started a mailing list, since it seems interest is growing, and people are having more questions: https://groups.google.com/forum/#!forum/beam-discussion

Feel free to join and ask for assistance with the backend.

Travis
