### ISSUE TITLE
`createSchema` from an `instance Database Postgres MyDatabase`

### ISSUE THREAD

**Issue by o1lo01ol1o** [tathougies/beam#242]
Given [this bit of code](https://github.com/tathougies/beam/blob/master/beam-migrate/Database/Beam/Migrate/Simple.hs#L190), it seems like creating the database or at least dumping a schema to a file should be doable.  But presently I can't figure out where in the `beam-migrate` I could splice in my database without setting up all the `beam-migrate-cli` bits.  

Could someone advise?

**Comment by o1lo01ol1o** [comment]
Ah, great, settled for generating the schema scripts and manually creating the schema, but this is better.  Thanks!

**Comment by Znack** [comment]
Here I have [a tiny example](https://github.com/Znack/beam-demoblog/blob/ba3243ff709f57dae6c076a698235ffa3f0b4243/src/Schema/Mutate.hs#L67-L70) of how migrations can be set up. There I use `bringUpToDateWithHooks` because it's much more powerful command: beam create two separate tables in DB `beam_migration` and `beam_version` where beam store all applied migrations and current version of beam migration system (for future significant beam upgrades).
Notice, that current Beam version (at now it is 0.7.2.1) suppose that even `createTable` is irreversible (or it is my stupid mistake somewhere, that's extremely possible), so I have set `runIrreversibleHook = pure True` in hooks.
I would recommend to play with example: apply all migrations with `runIrreversibleHook = pure False` (especially if current beam version will be newer), try to migrate both migrations, than try to migrate only first migration, and then with separate command migrate the whole migration composition. You can migrate only first migration with little modification of `Schema.Mutate` in my file:
```haskell
  runBeamPostgres
    conn
    (bringUpToDateWithHooks
       verboseHooks
       migrationBackend
       (migrationStep "Add user and author tables" V0001.migration))
```
