### ISSUE TITLE
LIMIT becomes 0 in generated SQL

### ISSUE THREAD

**Issue by rnons** [tathougies/beam#276]
I have a query that looks like the following, real code is [here](https://github.com/rnons/ted2srt/blob/master/backend/src/Models/Talk.hs#L66)

```
  runBeamPostgresDebug putStrLn dbConn $ do
    runSelectReturningList $ select
      ( offset_ (fromIntegral 20)
      $ limit_ (fromIntegral 20)
      $ orderBy_ (\t -> desc_ (_talkId t))
      $ all_ (_talk talkDb)
      )
```

The generated SQL is 
```
SELECT "t0"."id" AS "res0", "t0"."name" AS "res1", "t0"."slug" AS "res2", "t0"."filmed_at" AS "res3", "t0"."published_at" AS "res4", "t0"."description" AS "res5", "t0"."image" AS "res6", "t0"."languages" AS "res7", "t0"."media_slug" AS "res8", "t0"."media_pad" AS "res9"
FROM "talk" AS "t0" ORDER BY "t0"."id" DESC LIMIT 0 OFFSET 20
```

Notice the `LIMIT 0`

**Comment by mulderr** [comment]
I think I've seen this as well. [This](https://github.com/tathougies/beam/blob/5c8d96ae9a9f930a2f860bf282fb6954ce697bcf/beam-core/Database/Beam/Query/SQL92.hs#L148) looks related.

**Comment by 3noch** [comment]
I'd guess that flipping the order (`limit_` then `offset_`) might get around this. But I think order should not matter.

**Comment by rnons** [comment]
Thanks for clarification. It's still a bit surprising to me, easy to introduce bug since it's different from SQL semantics.

**Comment by 3noch** [comment]
@tathougies I agree that that is surprising. Perhaps you'd consider renaming them to `take_` and `drop_` instead? This would remove the expectation that the order doesn't matter, as is true in (at least some?) SQLs.

**Comment by 3noch** [comment]
And possibly as a followup make the order of `limit_` and `offset_` *not* matter.

**Comment by tathougies** [comment]
I could deprecate and rename, but there's no way you can make the order not matter unless you're willing to give up composability. The issue is straightforwards. Ignoring parameters that don't matter:

```haskell
-- | Returns the top 20 records
top20Records :: Q (QExprTable RecordT)
top20Records = limit_ 20 $ ...

-- | Returns the records in the 10 - 20 spot
records10To20 :: Q (QExprTable RecordT)
records10To20 = offset_ 10 top20Records
```

If you change the behavior to be what you want, then `limit_ 20 $ offset_ 10 == offset_ 10 $ limit_ 20`, This means that (surprisingly!), 'records10To20` would return the 20 records after the first 10, instead of the second 10 in the first set of 20.

The above example is somewhat contrived, since both queries are written next to each other, but if you imagine that `top20Records` is in a separate (hidden) module which you don't have access to in the current package, you would expect that no matter what transformations you apply to it, you cannot affect what results that query would return. If we allowed your change, then it could. This makes it a leaky abstraction.

The key point of confusion here is that postgres's and sqlite's `LIMIT x OFFSET y` clause always does the equivalent of `limit_ x $ offset_ y $ <query>`. It is rare that you write the SQL equivalent of `offset_ x $ limit_ y $ <query>` because that involves writing a sub select. Beam handles this for you.

**Comment by ocharles** [comment]
I think Beam using the list monad as a model is the right thing to do, fwiw. That means the original behavior is correct. If anything, it suggests `limit` and `offset` are renamed to `take` and `drop`.

**Comment by 3noch** [comment]
@tathougies Ah, then you are absolutely right to keep that behavior. I still think renaming to Haskell-like names would essentially solve this problem. It also follows from many of your other naming choices (like `isJust_` instead of `IS NOT NULL`).
