### ISSUE TITLE
Should boolean column types be supported?

### ISSUE THREAD

**Issue by timbod7** [tathougies/beam#3]
```
src/UserService/DB.hs:27:10:
    No instance for (FieldSchema Bool)
      arising from a use of ‘beam-0.3.0.0:Database.Beam.Schema.Tables.$gdmtblFieldSettings’
    In the expression:
      beam-0.3.0.0:Database.Beam.Schema.Tables.$gdmtblFieldSettings
    In an equation for ‘tblFieldSettings’:
        tblFieldSettings
          = beam-0.3.0.0:Database.Beam.Schema.Tables.$gdmtblFieldSettings
    In the instance declaration for ‘Table UserT’
```

**Comment by aspidites** [comment]
Disclaimer: I'm not the author of this library. 

While investigating this, I noticed that beam relies on HDBC's [SqlColDesc](https://hackage.haskell.org/package/HDBC-2.4.0.1/docs/Database-HDBC-ColTypes.html#t:SqlColDesc) to define HasDefaultFieldSchema instances. HDBC, in turn, relies on mostly ODBC to define [SqlTypeId](https://hackage.haskell.org/package/HDBC-2.4.0.1/docs/Database-HDBC-ColTypes.html#t:SqlTypeId)s. A bit of googling suggests that since SQL doesn't typically handle bools, ODBC hasn't either. I know that MySQL represents a bool as a tiny int, so it's not entirely unsurprising.

Whether or not that means this *can't* be supported is another matter, but I suspect that's why it hasn't been.

**Comment by tathougies** [comment]
Author here. @aspidites is right. Since there's no `SqlBoolT`, we can't support a backend-neutral boolean type. You could define your own `FieldSchema` (let's call it `boolSchema`) that used an integer behind the  scenes and then an instance for `FromSqlValues` for `Bool` which could correctly marshal between the SQL type and the Haskell type.

For example,

```haskell

boolSchema :: FieldSchema Bool
boolSchema = FieldSchema {  { fsColDesc = notNull SqlColDesc
                                          { colType = SqlNumericT
                                          , colSize = Nothing
                                          , colOctetLength = Nothing
                                          , colDecDigits = Nothing
                                          , colNullable = Nothing }
                            , fsHumanReadable = "boolSchema"
                            , fsMakeSqlValue = ..
                            , fsFromSqlValue = .. }

instance FromSqlValues Bool -- To get marshalling. Should work automatically

instance Table UserT where
    tblFieldSettings = UserT defFieldSchema
                             defFieldSchema -- Use `defFieldSchema` for all the fields that you want defaulted to the regular type
                             boolSchema -- Since there's no default for Bool types, use boolSchema for the Bool field
                             defFieldSchema
                             ...
```

If you want to default to the boolean schema you just made for your field, you can define an instance of `HasDefaultFieldSchema`.

I'm working on improving handling for default fields in the next version. I'm doing this by allowing backends to override more parts of beam's defaults. This will allow backends that support booleans natively to correctly choose a sensible type. Of course, you could always override them using the mechanism described above.

Thanks for reporting the issue, when I get around to implementing support for more than just sqlite (should be soon), I'll include a default boolean type for databases that support it.

**Comment by tathougies** [comment]
Boolean is now supported in back ends that allow it, but not as part of standard sql, which doesn't have a Boolean data type
