### ISSUE TITLE
`in_` breaking on list of foreign keys

### ISSUE THREAD

**Issue by cbeav** [tathougies/beam#333]
New to `beam`, love it.

Seeing a weird issue trying to use `in_` to generate the where clause on a delete. Got a table defined like such:

```haskell
data MembershipT f
  = Membership
  { membershipId      :: Columnar f (SqlSerial Int)
  , membershipUserId  :: PrimaryKey UserT f
  , membershipGroupId :: PrimaryKey GroupT f
  } deriving Generic
```

I want to delete all `Membership`s for a list of `GroupId = PrimaryKey GroupT Identity`.

This is unhappy:
```haskell
    runDelete $ delete (memberships db) $ \m ->
      membershipGroupId m `in_` map val_ groupIds
```

and throws

```bash
    • Couldn't match expected type ‘QGenExpr
                                      QValueContext
                                      Database.Beam.Postgres.Syntax.PgExpressionSyntax
                                      s
                                      a0’
                  with actual type ‘PrimaryKey
                                      GroupT
                                      (QExpr Database.Beam.Postgres.Syntax.PgExpressionSyntax s'0)’
```

However, this typechecks just fine, using the only `Columnar` we've got on the model:

```haskell
    runDelete $ delete (memberships db) $ \m ->
      membershipId m `in_` []
```

Anything obvious I'm missing here, or anything off with the way I've set up the FK relationship? Please and thanks!

**Comment by tathougies** [comment]
Hello Chris,

You can't use a `PrimaryKey` type with `in_`. You have to unwrap the primary key and match on the individual field.

The reason is that primary keys are not necessarily one field. It is possible to have arbitrary numbers of fields in a primary key. However, `in_` works with scalar values (at least ANSI SQL `IN` does). So, if you have a primary key like

```haskell
data PrimaryKey GroupT f = GroupKey { _groupKeyField1 :: Columnar f Text, _groupKeyField2 :: Columnar f Int }
```

then, you'd be expecting `in_` to match on two fields at once.

The way to get around this is to explicitly match on the `PrimaryKey` constructor and unwrap the scalar `Columnar` value inside. You can view this unwrapping as a proof to beam that the primary key only contains one field.

So replace

```haskell
    runDelete $ delete (memberships db) $ \m ->
      membershipGroupId m `in_` map val_ groupIds
```

with

```haskell
    runDelete $ delete (memberships db) $ \m ->
      let GroupKey aBetterName = membershipGroupId m 
      in aBetterName `in_` map val_ groupIds
```

**Comment by cbeav** [comment]
Oh duhhhhhh, okay that really unlocks some things for me. Much appreciated on the quick response!

**Comment by pdavidow** [comment]
Kindly update doc to discuss this issue. I have needlessly wasted plenty of time on this.

**Comment by kmicklas** [comment]
@pdavidow Can you explain how we can make the docs more clear? `beam-postgres` and `beam-sqlite` should both support this now.

**Comment by pdavidow** [comment]
@kmicklas Nevermind, I now see the _Note_ at https://tathougies.github.io/beam/user-guide/expressions/#the-in-predicate
