### ISSUE TITLE
Feature request: PostgreSQL LATERAL JOIN support

### ISSUE THREAD

**Issue by iand675** [tathougies/beam#353]
I have an application that uses `INNER LATERAL JOIN`s very extensively,  and there's presently no Haskell SQL generation library that supports them well. I'd very much like to move to Beam, and this is one of the few things that would prevent a full migration.

**Comment by tathougies** [comment]
Beam has supported this in the beam-0.8.0.0 branch since June :). Use `lateral_` from `Database.Beam.Postgres.Full`

I realize it may have been hard to find because it wasn't documented. I've added haddock documentation in the latest [commit](https://github.com/tathougies/beam/commit/d9dd86e074ca7221efe6739cbf122e1103e4e3f6)
