### ISSUE TITLE
Beam.FromBackendRow Beam.Sqlite String missing

### ISSUE THREAD

**Issue by moll** [tathougies/beam#368]
Took me a while to grok that a missing `FromBackendRow` instance didn't signal that type inference had gone awry, but instead that Beam doesn't know how to convert from SQLite's text to a Haskell `String` type. That seems to be caused by a missing `String` instance.

The following orphan instance fixes it:
```
instance Beam.FromBackendRow Beam.Sqlite String
```

While on the topic, I must say the type class `FromBackendRow` isn't well named in my view. It hints it's to do with whole rows, yet it's equally the machinery for parsing and serializing types to SQL. `ParseSql` or `FromSql` or something in that order would be a more understandable name, I think.

**Comment by kmicklas** [comment]
Using `String` in Haskell is generally a bad idea because it is just `[Char]`. This causes a number of issues, including slow code, confusing error messages, and, particularly relevant here, issues with instances. Although Sqlite does not support arrays, you could in principle imagine it adding support and then wanting an instance like `FromBackendRow Sqlite a => FromBackendRow Sqlite [a]`, which would then conflict with the `String` instance. `Text` is usually what you should use instead. I'm closing this for now but if you think the type error was sufficiently confusing reopen it and we can probably add a custom type error for GHC >= 8.4.
