### ISSUE TITLE
Can't create "all_" query

### ISSUE THREAD

**Issue by SamuraiJack** [tathougies/beam#43]
I'm probably missing something, but I could not create a basic "all_" query, following the tutorial.

Attaching a sample project, the compilation error is shown below. Please see "app/Main.hs" for a failing line.

I'm using "nextgen-beam-migrate" branch, the DB schema is generated by the "beam-migrate".

```
/home/nickolay/workspace/Haskell/simple/app/Main.hs:10:9: error:
        • Couldn't match type ‘Database.Beam.Backend.SQL.SQL92.Sql92FromExpressionSyntax
                                 (Database.Beam.Backend.SQL.SQL92.Sql92SelectTableFromSyntax
                                    (Database.Beam.Backend.SQL.SQL92.Sql92SelectSelectTableSyntax
                                       select0))’
                         with ‘Database.Beam.Backend.SQL.SQL92.Sql92SelectTableExpressionSyntax
                                 (Database.Beam.Backend.SQL.SQL92.Sql92SelectSelectTableSyntax
                                    select0)’
            arising from a use of ‘all_’
          The type variable ‘select0’ is ambiguous
        • In the expression: all_ (_table2 db)
          In an equation for ‘query’: query = all_ (_table2 db)
        • Relevant bindings include
            query :: Q select0
                       be
                       db0
                       s
                       (table0 (QExpr
                                  (Database.Beam.Backend.SQL.SQL92.Sql92SelectTableExpressionSyntax
                                     (Database.Beam.Backend.SQL.SQL92.Sql92SelectSelectTableSyntax
                                        select0))
                                  s))
              (bound at app/Main.hs:10:1)
```
[simple.tar.gz](https://github.com/tathougies/beam/files/1222555/simple.tar.gz)

**Comment by tathougies** [comment]
The type variable is ambiguous. The compiler wants it due to the monomorphism restriction. You need to either explicitly type the query with a concrete `SELECT` syntax to use or declare the query polymorphic.

If you want the compiler to infer the type, you have to use the query with a particular backend somewher in the program.

Here's one way to explicitly type it polymorphically, using type holes:

```
query :: forall select s. Q select _ _ s _
```

You'll likely get constraints missing on the `select` type variable. This is expected.  In order to run the query, the backend `SELECT` syntax will need to meet certain requirements, and these constraints will make sure of that.

Does that make sense?

**Comment by SamuraiJack** [comment]
Hm.. Theoretically it perfectly does. However, for me just trying to get my "hands dirty" and dump some sql, its a bit  overwhelming. As I understand, to be able to treat the query as something "materialized" it has to belong to some backend. 

With the purpose of just dumping the sql, how do I declare such query?

**Comment by tathougies** [comment]
The generated query is going to depend on the backend in use. Moreover, for certain backends -- such as postgres -- the query generated depends on the connection itself, due to connection-specific string escaping behavior. Thus, there's no canonical representation of a SQL statement.

The [tutorial](http://tathougies.github.io/beam/tutorials/tutorial1/) shows several strategies for dumping SQL. Firstly, you can dump the statements beam is about to run using `withDatabaseDebug` and passing in an appropriate logging function.

As the [manual](http://tathougies.github.io/beam/user-guide/queries/basic/) describes, you can also use an internal debug representation of the query to dump out a SQL-92 like expression. This query should not be used to execute the statement, due to backend-specific-escaping concerns.

To quote

```
dumpSqlSelect (all_ (persons exampleDb))
```

**Comment by SamuraiJack** [comment]
After changing to 
```
{-# LANGUAGE TypeOperators, OverloadedStrings, PartialTypeSignatures #-}

module Main where

import Schema
import Database.Beam

import Database.Beam.Postgres

import Lib


main :: IO ()
main = dumpSqlSelect (all_ (_table2 db))
```
there's still plenty of type failures..

**Comment by SamuraiJack** [comment]
Can you perhaps check the attached archive with sample project? Its stack-based, and supposed to be unpacked inside the top beam directory, near the "beam-core", "beam-migrate" folders (which are on the latest of next-gen-beam-migrate branch). I must be missing something obvious probably.

**Comment by tathougies** [comment]
The first problem is:

```
Found hole:
        _table2
          :: DatabaseSettings be0 Schema.Db
             -> DatabaseEntity be db0 (TableEntity table0)
```

The `Database` constructor isn't exported from `Schema.hs`. This is a bug in the code generation. You can go ahead and modify the file directly, and I will upload a patch later today.

So, to be clear, change

```
module Schema (db, migration) where
```

to

```
module Schema (Db(...), db, migration) where
```

The second problem is that the `beam-migrate` utility generates a migratable database, which is a bit more complicated than what `SqlSyntaxBuilder` allows. I'll work on this today, and upload a patch this evening. Sorry about that.

In the meantime, you can try using the `withDatabaseDebug` technique to execute against a database.

**Comment by SamuraiJack** [comment]
Thanks for the help! I'll continue tomorrow.

**Comment by tathougies** [comment]
Try now... I think I got it working on my laptop

```
$ stack exec -- simple-exe
SELECT `t0`.`id` AS "res0", `t0`.`fkColumn` AS "res1" FROM "table2" AS "t0"
```

**Comment by SamuraiJack** [comment]
Hm.. Same branch? Doesn't work for me:

```
[2 of 2] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/simple-exe/simple-exe-tmp/Main.o )
    
    /home/nickolay/workspace/Haskell/simple/app/Main.hs:14:37: error:
        • Couldn't match type ‘Database.Beam.Migrate.SQL.SQL92.Sql92AlterTableColumnSchemaSyntax
                                 (Database.Beam.Migrate.SQL.SQL92.Sql92AlterTableAlterTableActionSyntax
                                    (Database.Beam.Migrate.SQL.SQL92.Sql92DdlCommandAlterTableSyntax
                                       syntax0))’
                         with ‘Database.Beam.Migrate.SQL.SQL92.Sql92CreateTableColumnSchemaSyntax
                                 (Database.Beam.Migrate.SQL.SQL92.Sql92DdlCommandCreateTableSyntax
                                    syntax0)’
            arising from a use of ‘db’
          The type variable ‘syntax0’ is ambiguous
        • In the first argument of ‘_table2’, namely ‘db’
          In the first argument of ‘all_’, namely ‘(_table2 db)’
          In the first argument of ‘dumpSqlSelect’, namely
            ‘(all_ (_table2 db))’
```

**Comment by tathougies** [comment]
You pulled the latest `beam-core`? Sometimes you have to do `stack clean beam-core` to have it rebuild

**Comment by SamuraiJack** [comment]
Yes, works after "stack clean"! Yay :) Thanks for the help, I'll be figuring the next step..

**Comment by tathougies** [comment]
@SamuraiJack  Wonderful! Can I close this issue, then?

**Comment by SamuraiJack** [comment]
Yes, sure.
