### ISSUE TITLE
beam-sqlite won't build with GHC 8.8

### ISSUE THREAD

**Issue by kozross** [tathougies/beam#459]
Unlike the other packages in this repo, its `hashable` is still hard-bounded below `1.3`.

**Comment by kmicklas** [comment]
How does this relate to GHC 8.8? I was able to build with GHC 8.8 and `hashable` 1.2.7.0. Regardless, the bound should probably be bumped.

**Comment by kozross** [comment]
@kmicklas Unless I'm misreading, `hashable-1.2.7.0` [has the following bounds][1]: ``base (>=4.4 && <4.13)``. That shouldn't be buildable with 8.8 (and in fact, in our case, wasn't).

[1]: http://hackage.haskell.org/package/hashable-1.2.7.0

**Comment by kmicklas** [comment]
Ah you're right, it was building for me only because I used nixpkgs which removes the version bounds for `hashable` on GHC 8.8: https://github.com/NixOS/nixpkgs/blob/af7709afc749ec8e98ba807cce8c4004f51489b9/pkgs/development/haskell-modules/configuration-ghc-8.8.x.nix#L60

I'll put up a PR to loosen it for `beam-core` and `beam-migrate-cli` which also needs it.

**Comment by kozross** [comment]
@kmicklas Amusingly enough, we encountered the exact same mix-up!
