### ISSUE TITLE
Couldn't match kind '* -> *' with *

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#65]
I'm seeing this compile error from time to time:

```
Couldn't match kind '* -> *' with '*'
When matching the kind of 'UserT'
Expected type: m (Maybe User)
  Actual type: m (Maybe (UserT Identity))
```

I have `type User = UserT Identity` so I have no idea why this error makes sense. I'm on GHC 8.0.2.

**Comment by tathougies** [comment]
This seems like a bug in GHC. Does it work in 8.2?

**Comment by 3noch** [comment]
Unfortunately I won't be able to test that for a while. I wouldn't be surprised if you're right.

**Comment by tathougies** [comment]
Do you have any example I could try to reproduce?

**Comment by vwwv** [comment]
I've got a similar issue a couple of times, where ghc was complaining `Couldn't match kind '* -> *' with '*'` then showing exactly the same types as expected and actual. In my case, It ended up being something totally unrelated to beam:

   In one case, by error, I used a constraint (`* -> Constraint`) in a type application expecting a type (`*`), in the other case I was using a map (`* -> * -> *`) in a list comprehension instead of a list (`* -> *`).

In both cases, the error was marked on a different line it actually happened, and over a type that has not much to do with it, making it something really frustrating to debug even though they were pretty dumb bugs. I think, somehow, on some ghc versions, ghc's error report heuristic doesn't play well in some situations where beam's columnar approach (i.e `C f Foo`) is involved.

In my case, I was using `ghc-8.0.2`, maybe this has improved in later ghc versions?
